//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKIM_PROJESİ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Takim()
        {
            this.Oyuncu = new HashSet<Oyuncu>();
        }
    
        public int TakimNo { get; set; }
        public string TakimAdi { get; set; }
        public int UlkeNo { get; set; }
    
        public virtual Ulke Ulke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oyuncu> Oyuncu { get; set; }
    }
}
